PREFIX pf: <http://localhost:8080/openrdf-sesame/repositories/001#>
SELECT ?friend(COUNT(?friend) as ?popularity)
{
  ?person pf:friend    ?friend.
}
GROUP BY ?friend
ORDER BY DESC(?popularity)
LIMIT 1
